on: 
    workflow_dispatch:
    pull_request:
        types: [opened, reopened]
        branches:
        - "main"        
    pull_request_review:
        types: [submitted]  
    push:
        branches:
        - "main"
        - "*Baseline*"
        paths:
        - "baselines/*.md"

name: Markdown Check
  
jobs:
    Run-Markdown-Check:
        runs-on: windows-latest
        defaults:
            run:
                shell: powershell 
        permissions:
            contents: read
        steps:
        - name: Checkout repo code
          uses: actions/checkout@v3
        - name: Execute markdown checks
          run: |
            $PSVersionTable
            Invoke-Pester Testing\Unit\PowerShell\CreateReport -Output Detailed