name: Run PowerShell Tests
on:
  # Run tests on each commit, newly opened/reopened PR, and
  # PR review submission (e.g. approval)
  workflow_dispatch:
  push:
    paths:
      - "**.ps1"
      - "**.psm1"
      - ".github/workflows/run_powershell_tests.yaml"
  pull_request:
    types: [opened, reopened]
    branches:
      - "main"
    paths:
      - "**.ps1"
      - "**.psm1"
  pull_request_review:
    types: [submitted]

jobs:
  Run-PowerShell-Tests:
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Run Pester Tests
      if: '!cancelled()'
      shell: powershell
      run: |
        ./SetUp.ps1 -NoOpa
        Invoke-Pester -Output 'Detailed' -Path './Testing/Unit/PowerShell'
