on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: "Release Name"
        required: true
        type: string
      version:
        description: "Release Version (e.g., 1.2.4)"
        required: true
        type: string

name: Build and Sign Release

jobs:
  build-and-deploy:
    runs-on: windows-latest
    env:
      SCUBA_CODE_SIGNING_CREDS: ${{ secrets.SCUBA_CODE_SIGNING_CREDS }}
      CODESIGN_PW: ${{ secrets.CODESIGN_PW }}
      CODESIGN_PFX: ${{ secrets.CODESIGN_PFX }}
      RELEASE_VERSION: ${{ inputs.version }}
    permissions:
      contents: write
    steps:
      - name: Install AzureSignTool
        shell: pwsh
        run: |
          dotnet --version
          dotnet tool install --global AzureSignTool --version 4.0.1
          $CREDS = $env:SCUBA_CODE_SIGNING_CREDS | ConvertFrom-Json
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo
      - name:     

